{
    "type": "bundle",
    "id": "bundle--7a00bee5-5b93-41df-9dc4-ac04e57da2d5",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--792e8578-6b79-46f5-9345-2308454384e2",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-12-12T01:16:45.906632Z",
            "modified": "2024-12-12T01:16:45.906632Z",
            "name": "CVE-2024-54513",
            "description": "A permissions issue was addressed with additional restrictions. This issue is fixed in watchOS 11.2, visionOS 2.2, tvOS 18.2, macOS Sequoia 15.2, iOS 18.2 and iPadOS 18.2. An app may be able to access sensitive user data.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-54513"
                }
            ]
        }
    ]
}