{
    "type": "bundle",
    "id": "bundle--b2b281e7-1ebf-4c05-9a3b-31aa1f9dedc7",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--12022b32-a25d-4e6c-b7bf-401095048330",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-05-09T01:20:28.621482Z",
            "modified": "2025-05-09T01:20:28.621482Z",
            "name": "CVE-2025-37825",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nnvmet: fix out-of-bounds access in nvmet_enable_port\n\nWhen trying to enable a port that has no transport configured yet,\nnvmet_enable_port() uses NVMF_TRTYPE_MAX (255) to query the transports\narray, causing an out-of-bounds access:\n\n[  106.058694] BUG: KASAN: global-out-of-bounds in nvmet_enable_port+0x42/0x1da\n[  106.058719] Read of size 8 at addr ffffffff89dafa58 by task ln/632\n[...]\n[  106.076026] nvmet: transport type 255 not supported\n\nSince commit 200adac75888, NVMF_TRTYPE_MAX is the default state as configured by\nnvmet_ports_make().\nAvoid this by checking for NVMF_TRTYPE_MAX before proceeding.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-37825"
                }
            ]
        }
    ]
}