{
    "type": "bundle",
    "id": "bundle--362e0b3a-a546-4d51-9ee4-8fd54f6367e4",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--f225bdbf-ff19-4d6b-abc6-c63b5dbac5e3",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-10-22T01:11:23.557111Z",
            "modified": "2024-10-22T01:11:23.557111Z",
            "name": "CVE-2024-47723",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\njfs: fix out-of-bounds in dbNextAG() and diAlloc()\n\nIn dbNextAG() , there is no check for the case where bmp->db_numag is\ngreater or same than MAXAG due to a polluted image, which causes an\nout-of-bounds. Therefore, a bounds check should be added in dbMount().\n\nAnd in dbNextAG(), a check for the case where agpref is greater than\nbmp->db_numag should be added, so an out-of-bounds exception should be\nprevented.\n\nAdditionally, a check for the case where agno is greater or same than\nMAXAG should be added in diAlloc() to prevent out-of-bounds.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-47723"
                }
            ]
        }
    ]
}