{
    "type": "bundle",
    "id": "bundle--e606e997-7e8e-4441-bc8c-54c2c232f9fb",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--b15a1ebc-a7d3-41c6-a5dd-df93bbf68365",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-04T01:16:14.851957Z",
            "modified": "2025-04-04T01:16:14.851957Z",
            "name": "CVE-2025-32049",
            "description": "A flaw was found in libsoup. The SoupWebsocketConnection may accept a large WebSocket message, which may cause libsoup to allocate memory and lead to a denial of service (DoS).",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32049"
                }
            ]
        }
    ]
}