{
    "type": "bundle",
    "id": "bundle--8e1b6809-22d2-40a8-8fed-3144ea1a8d56",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--3fa1520b-d533-4186-bc67-8894d389b9dc",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-01-22T01:10:46.869414Z",
            "modified": "2025-01-22T01:10:46.869414Z",
            "name": "CVE-2024-49747",
            "description": "In gatts_process_read_by_type_req of gatt_sr.cc, there is a possible out of bounds write due to a logic error in the code. This could lead to remote code execution with no additional execution privileges needed. User interaction is not needed for exploitation.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-49747"
                }
            ]
        }
    ]
}