{
    "type": "bundle",
    "id": "bundle--d9b597d4-ccce-42fd-9947-24378ebc1394",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--b3fa2dcf-22eb-440e-bde8-2e248ff9983d",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-02T00:55:35.182979Z",
            "modified": "2024-05-02T00:55:35.182979Z",
            "name": "CVE-2024-27047",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nnet: phy: fix phy_get_internal_delay accessing an empty array\n\nThe phy_get_internal_delay function could try to access to an empty\narray in the case that the driver is calling phy_get_internal_delay\nwithout defining delay_values and rx-internal-delay-ps or\ntx-internal-delay-ps is defined to 0 in the device-tree.\nThis will lead to \"unable to handle kernel NULL pointer dereference at\nvirtual address 0\". To avoid this kernel oops, the test should be delay\n>= 0. As there is already delay < 0 test just before, the test could\nonly be size == 0.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-27047"
                }
            ]
        }
    ]
}