{
    "type": "bundle",
    "id": "bundle--ce75c0d0-93e5-4b99-a728-f1d560bd53a4",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--391921e4-7ba9-471b-bdf2-64a66104ca7b",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-08-23T01:03:38.962649Z",
            "modified": "2024-08-23T01:03:38.962649Z",
            "name": "CVE-2024-45201",
            "description": "An issue was discovered in llama_index before 0.10.38. download/integration.py includes an exec call for import {cls_name}.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-45201"
                }
            ]
        }
    ]
}