{
    "type": "bundle",
    "id": "bundle--b2b28cb5-907c-42e0-89da-00cb4d8a57c0",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--75dbe1aa-cdd0-4b02-beb6-85bd8acad316",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-12-30T01:13:11.753289Z",
            "modified": "2024-12-30T01:13:11.753289Z",
            "name": "CVE-2024-56630",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nocfs2: free inode when ocfs2_get_init_inode() fails\n\nsyzbot is reporting busy inodes after unmount, for commit 9c89fe0af826\n(\"ocfs2: Handle error from dquot_initialize()\") forgot to call iput() when\nnew_inode() succeeded and dquot_initialize() failed.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-56630"
                }
            ]
        }
    ]
}