{
    "type": "bundle",
    "id": "bundle--87536d11-37a9-4a9a-8be9-905e126e6d13",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--69dd4e54-62b0-4617-83e6-3fd50f2e36b3",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-10-02T01:10:12.332973Z",
            "modified": "2024-10-02T01:10:12.332973Z",
            "name": "CVE-2024-8421",
            "description": "This CVE has been rejected.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-8421"
                }
            ]
        }
    ]
}